// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ParkLookUpAPI.Models;

namespace ParkLookUpAPI.Migrations
{
    [DbContext(typeof(ParkLookUpAPIContext))]
    partial class ParkLookUpAPIContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("ParkLookUpAPI.Models.Park", b =>
                {
                    b.Property<int>("ParkId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Area")
                        .HasColumnType("int");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<bool>("IsOpen")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("ParkId");

                    b.ToTable("Parks");

                    b.HasData(
                        new
                        {
                            ParkId = 1,
                            Area = 2219789,
                            City = "West Yellowstone",
                            IsOpen = true,
                            Name = "Yellow Stone",
                            State = "Wyoming"
                        },
                        new
                        {
                            ParkId = 2,
                            Area = 265461,
                            City = "Estes Park",
                            IsOpen = true,
                            Name = "Rocky Moutain",
                            State = "Colorado"
                        },
                        new
                        {
                            ParkId = 3,
                            Area = 183224,
                            City = "Klamath Falls",
                            IsOpen = false,
                            Name = "Crater Lake",
                            State = "Oregon"
                        },
                        new
                        {
                            ParkId = 4,
                            Area = 236381,
                            City = "Tacoma",
                            IsOpen = true,
                            Name = "Mount Rainier",
                            State = "Washington"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
